"""Executive deliverables: a multi-page PDF and a multi-sheet Excel workbook.

Both build entirely from the deterministic :func:`logitwin.analysis.full_report` output and return
raw ``bytes``. Nothing is fetched from the network; matplotlib and openpyxl render locally.
"""

from __future__ import annotations

import io

import matplotlib

matplotlib.use("Agg")  # headless / no display
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.backends.backend_pdf import PdfPages  # noqa: E402
from openpyxl import Workbook  # noqa: E402
from openpyxl.styles import Font  # noqa: E402

from .analysis import full_report, headline_numbers  # noqa: E402

DISCLAIMER = (
    "All figures are produced from SYNTHETIC, deterministic (seeded) data generated by this "
    "project. They illustrate method and relative gains, not any real facility. Bin packing and "
    "slotting are NP-hard; results below are from heuristics (near-optimal on small instances) with "
    "measured optimality gaps reported. Not affiliated with any company named in supporting notes."
)

_NAVY = "#1f3a5f"
_TEAL = "#2a9d8f"
_AMBER = "#e9a03b"
_GREY = "#9aa5b1"


def _bar(ax, labels, values, colors, title, ylabel):
    bars = ax.bar(labels, values, color=colors)
    ax.set_title(title, fontsize=12, fontweight="bold")
    ax.set_ylabel(ylabel)
    ax.spines[["top", "right"]].set_visible(False)
    for b, v in zip(bars, values, strict=True):
        ax.text(
            b.get_x() + b.get_width() / 2,
            b.get_height(),
            f"{v:,.1f}",
            ha="center",
            va="bottom",
            fontsize=9,
        )
    return ax


def build_pdf(report: dict | None = None) -> bytes:
    """Render the multi-page executive PDF and return its bytes."""
    r = report or full_report()
    h = headline_numbers(r)
    p, s, sim = r["packing"], r["slotting"], r["simulation"]

    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        # --- Cover page ---
        fig = plt.figure(figsize=(11, 8.5))
        fig.patch.set_facecolor("white")
        fig.text(0.5, 0.88, "Warehouse Digital Twin", ha="center", fontsize=26, fontweight="bold", color=_NAVY)
        fig.text(0.5, 0.82, "Quantifying the Legacy-vs-Modern Operations Gap", ha="center", fontsize=14, color=_GREY)

        gains = [
            f"Container fill rate: {h['naive_fill_pct']}%  ->  {h['ffd_fill_pct']}%",
            f"Containers used: {h['naive_containers']}  ->  {h['ffd_containers']}  ({h['containers_saved']} saved)",
            f"Pick-travel (slotting): -{h['travel_reduction_pct']}%",
            f"Order cycle time (simulation): {h['legacy_cycle_s']}s  ->  {h['modern_cycle_s']}s  (-{h['cycle_time_reduction_pct']}%)",
            f"Picker travel (simulation): -{h['sim_travel_reduction_pct']}%",
            f"Re-slotting break-even: {h['break_even_days']} days ({h['n_moves']} moves)",
        ]
        y = 0.68
        fig.text(0.12, 0.73, "Headline gains (synthetic run)", fontsize=13, fontweight="bold", color=_NAVY)
        for g in gains:
            fig.text(0.14, y, "- " + g, fontsize=12)
            y -= 0.05

        fig.text(
            0.5,
            0.16,
            DISCLAIMER,
            ha="center",
            va="center",
            fontsize=8.5,
            color=_GREY,
            wrap=True,
        )
        pdf.savefig(fig)
        plt.close(fig)

        # --- Fill-rate before/after ---
        fig, ax = plt.subplots(figsize=(11, 8.5))
        _bar(
            ax,
            ["Naive\n(1 carton/container)", "FFD heuristic"],
            [h["naive_fill_pct"], h["ffd_fill_pct"]],
            [_GREY, _TEAL],
            "Container Fill Rate: Legacy vs Modern Packing",
            "Fill rate (%)",
        )
        ax.text(
            0.5,
            -0.12,
            f"Containers used: {p['naive_containers']} -> {p['ffd_containers']} "
            f"({p['containers_saved']} saved). FFD-1D matched CP-SAT optimum on the "
            f"{p['cpsat_small_instance_size']}-item check ({p['ffd_small_bins']} vs "
            f"{p['cpsat_small_bins']} bins, gap {p['cpsat_gap_pct']:.1f}%).",
            transform=ax.transAxes,
            ha="center",
            fontsize=9,
            color=_GREY,
        )
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        # --- Slotting travel before/after ---
        fig, ax = plt.subplots(figsize=(11, 8.5))
        _bar(
            ax,
            ["Legacy\n(alphabetical)", "Optimized\n(velocity)"],
            [s["legacy_travel"], s["optimized_travel"]],
            [_GREY, _NAVY],
            "Daily Pick Travel: Legacy vs Optimized Slotting",
            "Demand-weighted travel (unit-m/day)",
        )
        ax.text(
            0.5,
            -0.12,
            f"Travel reduction: {s['reduction_pct']:.1f}%. Re-slotting plan: {s['n_moves']} moves, "
            f"break-even in {s['break_even_days']:.1f} days.",
            transform=ax.transAxes,
            ha="center",
            fontsize=9,
            color=_GREY,
        )
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        # --- Simulation comparison ---
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 8.5))
        _bar(
            ax1,
            ["Legacy", "Modern"],
            [sim["legacy"].mean_cycle_time_s, sim["modern"].mean_cycle_time_s],
            [_GREY, _TEAL],
            "Mean Order Cycle Time",
            "seconds",
        )
        _bar(
            ax2,
            ["Legacy", "Modern"],
            [sim["legacy"].total_travel_m, sim["modern"].total_travel_m],
            [_GREY, _AMBER],
            "Total Picker Travel",
            "metres",
        )
        fig.suptitle(
            "Discrete-Event Simulation: Legacy vs Modern Regime",
            fontsize=13,
            fontweight="bold",
            color=_NAVY,
        )
        fig.text(
            0.5,
            0.04,
            f"{sim['orders']} orders / shift. Cycle time -{sim['cycle_time_reduction_pct']:.1f}%, "
            f"travel -{sim['travel_reduction_pct']:.1f}%. Hand-rolled heapq event queue, seeded.",
            ha="center",
            fontsize=9,
            color=_GREY,
        )
        pdf.savefig(fig)
        plt.close(fig)

        # --- Re-shuffle plan summary ---
        fig, ax = plt.subplots(figsize=(11, 8.5))
        ax.axis("off")
        ax.set_title("Re-Shuffle Plan Summary", fontsize=14, fontweight="bold", color=_NAVY, loc="left")
        moves = s["moves"][:18]
        lines = [
            f"Total moves to reach optimized layout: {s['n_moves']}",
            f"One-off cost: {s['one_off_cost_seconds']:.0f} picker-seconds",
            f"Daily saving: {s['daily_saving_seconds']:.0f} picker-seconds/day",
            f"Break-even: {s['break_even_days']:.1f} days",
            f"Plan validated (current -> target): {s['plan_valid']}",
            "",
            "First moves (SKU: from slot -> to slot):",
        ]
        for m in moves:
            lines.append(f"   {m.sku}:  slot {m.from_slot}  ->  slot {m.to_slot}")
        if s["n_moves"] > len(moves):
            lines.append(f"   ... and {s['n_moves'] - len(moves)} more")
        ax.text(0.02, 0.92, "\n".join(lines), va="top", ha="left", fontsize=10, family="monospace")
        pdf.savefig(fig)
        plt.close(fig)

    return buf.getvalue()


def build_excel(report: dict | None = None) -> bytes:
    """Render the multi-sheet Excel workbook and return its bytes."""
    r = report or full_report()
    h = headline_numbers(r)
    p, s, sim = r["packing"], r["slotting"], r["simulation"]

    wb = Workbook()

    def header(ws, cols):
        ws.append(cols)
        for c in ws[1]:
            c.font = Font(bold=True)

    # Summary
    ws = wb.active
    ws.title = "Summary"
    ws.append(["Warehouse Digital Twin - Executive Summary"])
    ws["A1"].font = Font(bold=True, size=14)
    ws.append(["All data synthetic and deterministic (seeded). Heuristics; NP-hard problems."])
    ws.append([])
    header(ws, ["Metric", "Legacy", "Modern", "Delta"])
    ws.append(["Container fill rate (%)", h["naive_fill_pct"], h["ffd_fill_pct"], f"+{h['ffd_fill_pct'] - h['naive_fill_pct']:.1f}pp"])
    ws.append(["Containers used", h["naive_containers"], h["ffd_containers"], -h["containers_saved"]])
    ws.append(["Pick travel reduction (slotting, %)", "-", "-", f"-{h['travel_reduction_pct']}%"])
    ws.append(["Mean order cycle time (s)", h["legacy_cycle_s"], h["modern_cycle_s"], f"-{h['cycle_time_reduction_pct']}%"])
    ws.append(["Picker travel reduction (sim, %)", "-", "-", f"-{h['sim_travel_reduction_pct']}%"])
    ws.append(["Re-slotting break-even (days)", "-", "-", h["break_even_days"]])

    # Packing
    ws = wb.create_sheet("Packing")
    header(ws, ["Metric", "Value"])
    for k, v in [
        ("Naive fill rate (%)", round(100 * p["naive_fill"], 2)),
        ("FFD fill rate (%)", round(100 * p["ffd_fill"], 2)),
        ("Naive containers", p["naive_containers"]),
        ("FFD containers", p["ffd_containers"]),
        ("Containers saved", p["containers_saved"]),
        ("CP-SAT check instance size", p["cpsat_small_instance_size"]),
        ("FFD-1D bins (small instance)", p["ffd_small_bins"]),
        ("CP-SAT optimal bins (small instance)", p["cpsat_small_bins"]),
        ("Heuristic gap vs optimal (%)", round(p["cpsat_gap_pct"], 2)),
    ]:
        ws.append([k, v])

    # Slotting
    ws = wb.create_sheet("Slotting")
    header(ws, ["Metric", "Value"])
    for k, v in [
        ("Legacy travel (unit-m/day)", round(s["legacy_travel"], 2)),
        ("Optimized travel (unit-m/day)", round(s["optimized_travel"], 2)),
        ("Travel saved", round(s["travel_saved"], 2)),
        ("Reduction (%)", round(s["reduction_pct"], 2)),
        ("Moves in re-shuffle plan", s["n_moves"]),
        ("Break-even (days)", round(s["break_even_days"], 2)),
        ("Plan validated", s["plan_valid"]),
    ]:
        ws.append([k, v])

    # Simulation
    ws = wb.create_sheet("Simulation")
    header(ws, ["Metric", "Legacy", "Modern"])
    lg, md = sim["legacy"], sim["modern"]
    ws.append(["Orders completed", lg.orders_completed, md.orders_completed])
    ws.append(["Mean cycle time (s)", round(lg.mean_cycle_time_s, 1), round(md.mean_cycle_time_s, 1)])
    ws.append(["P95 cycle time (s)", round(lg.p95_cycle_time_s, 1), round(md.p95_cycle_time_s, 1)])
    ws.append(["Total picker travel (m)", round(lg.total_travel_m, 1), round(md.total_travel_m, 1)])
    ws.append(["Container utilization (%)", round(100 * lg.container_utilization, 1), round(100 * md.container_utilization, 1)])
    ws.append(["Makespan (s)", round(lg.makespan_s, 1), round(md.makespan_s, 1)])

    # ReshufflePlan
    ws = wb.create_sheet("ReshufflePlan")
    header(ws, ["SKU", "From slot", "To slot"])
    for m in s["moves"]:
        ws.append([m.sku, m.from_slot, m.to_slot])

    # Cartons catalog (the full synthetic dataset for transparency).
    ds = r["dataset"]
    ws = wb.create_sheet("Cartons")
    header(ws, ["Carton ID", "SKU", "Length (cm)", "Width (cm)", "Height (cm)", "Weight (kg)", "Velocity", "Volume (cm3)"])
    for c in ds["cartons"]:
        ws.append([c.id, c.sku, c.length, c.width, c.height, c.weight, c.velocity, round(c.volume, 1)])

    # Slots with legacy and optimized SKU assignment.
    legacy_by_slot = {v: k for k, v in s["legacy_result"].assignment.items()}
    opt_by_slot = {v: k for k, v in s["optimized_result"].assignment.items()}
    ws = wb.create_sheet("Slots")
    header(ws, ["Slot ID", "Aisle", "Bay", "Level", "Distance (m)", "Legacy SKU", "Optimized SKU"])
    for sl in ds["warehouse"].slots:
        ws.append([
            sl.id, sl.aisle, sl.bay, sl.level, sl.distance,
            legacy_by_slot.get(sl.id, ""), opt_by_slot.get(sl.id, ""),
        ])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
